version: "3.8"
services:
  db:
    image: postgres # use latest official postgres version
    container_name: postgres-db
    env_file:
      - ./.env # configure postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data
    # hostname: postgres
    ports:
      - '5432:5432'
    # expose:
    #   - 5432
    networks:
      - mynet
    restart: always
    volumes:
      - db:/var/lib/postgresql/data # persist data even if container shuts down

  server:
    depends_on:
      - db
    # image: horizon5132/approve-me-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '8080:8080'
    # links:
    #   - db
    volumes:
      - './:/src'
      - 'server:/opt/jboss/wildfly/standalone/log'
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
volumes:
  # postgres-data-dev:
  #   driver: local
  db: # named volumes can be managed easier using docker-compose
  server:
