version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    env_file:
      - .env
    ports:
      - "8027:8027"
    command: start-dev
    volumes:
      - keycloak:/opt/keycloak/data/
    networks:
      - letsplay_net
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres # use latest official postgres version
    container_name: postgres-db
    env_file:
      - .env # configure postgres
    ports:
      - '5432:5432'
    networks:
      - letsplay_net
    restart: always
    volumes:
      - db:/var/lib/postgresql/data # persist data even if container shuts down

  server:
    container_name: server_be
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - './:/src'
      - './logs:/opt/jboss/wildfly/standalone/log'
      - '$GOOGLE_SERVICE_ACCOUNT_KEY_PATH_HOST:/opt/jboss/wildfly/standalone/configuration/key'
    networks:
      - letsplay_net
networks:
  letsplay_net:
    name: letsplay_net
    attachable: true
    driver: bridge
volumes:
  # postgres-data-dev:
  #   driver: local
  db: # named volumes can be managed easier using docker-compose
  server:
  keycloak:
