ALTER TABLE PUBLIC.Requests
ALTER COLUMN createdTime TYPE TIMESTAMP USING (createdTime::TIMESTAMP);

ALTER TABLE PUBLIC.Requests
ALTER COLUMN fromDate TYPE TIMESTAMP USING (fromDate::TIMESTAMP);

ALTER TABLE PUBLIC.Requests
ALTER COLUMN toDate TYPE TIMESTAMP USING (toDate::TIMESTAMP);