ALTER TABLE PUBLIC.Requests
ALTER COLUMN createdTime TYPE TIMESTAMP WITH TIME ZONE USING (createdTime::TIMESTAMP WITH TIME ZONE);
ALTER TABLE PUBLIC.Requests
ALTER COLUMN fromDate TYPE TIMESTAMP WITH TIME ZONE USING (createdTime::TIMESTAMP WITH TIME ZONE);
ALTER TABLE PUBLIC.Requests
ALTER COLUMN toDate TYPE TIMESTAMP WITH TIME ZONE USING (createdTime::TIMESTAMP WITH TIME ZONE);

SET TIME ZONE 'UTC';
INSERT INTO PUBLIC.Requests(createdTime, employeeId, fromDate, reason, requestType,toDate)
VALUES ('2022-12-16T12:00:00+00', '123', '2022-12-16T12:00:00+07','test reason', 'leave', '2022-12-16T12:00:00+07');
